# Generated by Django 2.2.7 on 2019-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
