# Generated by Django 2.2.7 on 2019-11-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20191113_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ('-date_modified',)},
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='classification_scheme',
        ),
    ]
