# Generated by Django 2.2.7 on 2019-11-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_auto_20191120_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='archive',
        ),
        migrations.AddField(
            model_name='criteria',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='additional_classification_scheme',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
