# Generated by Django 2.2.7 on 2020-02-10 11:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_auto_20191128_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='additional_classification_description',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='additional_classification_id',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='classification_description',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='classification_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='criteria',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date_modified'], name='criteria_cr_date_mo_1f6092_brin'),
        ),
    ]
