# Generated by Django 2.2.7 on 2020-02-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_auto_20200210_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
