# Generated by Django 2.2.7 on 2020-01-21 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
