# Generated by Django 2.2.7 on 2020-02-12 10:18

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200210_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classification_description',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classification_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('hidden', 'Hidden')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date_modified'], name='profiles_pr_date_mo_6eef56_brin'),
        ),
    ]
