version: '3'

services:
  db:
    image: postgres
    command: -p 5433
    expose:
      - "5433"
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - data-volume:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ./application:/code/application
      - ./criteria:/code/criteria
      - ./profiles:/code/profiles
      - ./standarts:/code/standarts
    environment:
      POSTGRES_DB: ecatalogue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5433
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  data-volume:
