POST /api/0/criteria/ HTTP/1.0
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 600
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "name": "Name",
  "nameEng": "Name eng",
  "classification": {
    "id": "92350000-9",
    "scheme": "ДК021",
    "description": "Послуги гральних закладів і тоталізаторів"
  },
  "additionalClassification": {
    "id": "03114100-4",
    "scheme": "ДК021",
    "description": "Солома"
  },
  "minValue": "11",
  "maxValue": "22",
  "dataType": "number",
  "unit": {
    "name": "millilitre of water",
    "code": "WW"
  }
}


201 Created
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 600
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "id": "7af62856004742cdb2189444a83a1ad7",
  "name": "Name",
  "nameEng": "Name eng",
  "minValue": 11.0,
  "maxValue": 22.0,
  "dataType": "number",
  "status": "active",
  "classification": {
    "description": "Послуги гральних закладів і тоталізаторів",
    "scheme": "ДК021",
    "id": "92350000-9"
  },
  "additionalClassification": {
    "description": "Солома",
    "id": "03114100-4",
    "scheme": "ДК021"
  },
  "unit": {
    "name": "millilitre of water",
    "code": "WW"
  },
  "dateModified": "2019-12-09T15:36:40.013247Z"
}