GET /api/0/profiles/?criteria_requirementGroups_requirements_relatedCriteria_id=d0f05bb77cab426b8828a952d27894d9 HTTP/1.0
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{}


200 OK
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": "5e9250a98fb8448190d0f6390ce665cd",
      "unit": {
        "name": "accounting unit",
        "code": "E50"
      },
      "value": {
        "valueAddedTaxIncluded": true,
        "amount": 50.0,
        "currency": "UAH"
      },
      "criteria": [
        {
          "id": "28d677b2031d4290922553175bf8ac52",
          "requirementGroups": [
            {
              "id": "9a0cefb5d7cd4a2884a9813cb6b36252",
              "requirements": [
                {
                  "relatedCriteria_id": "d0f05bb77cab426b8828a952d27894d9",
                  "expectedValue": "5",
                  "title": "Test requirement",
                  "description": "Test requirement description"
                }
              ],
              "description": "Test requirement group"
            }
          ],
          "description": "Test description",
          "title": "Test criteria"
        }
      ],
      "images": [
        {
          "sizes": "228",
          "url": "https://test.url"
        }
      ],
      "dateModified": "2020-02-14T13:19:19.537013Z",
      "classification": {
        "description": "Послуги гральних закладів і тоталізаторів",
        "scheme": "ДК021",
        "id": "92350000-9"
      },
      "additionalClassification": [
        {
          "description": "Кишкові щипці",
          "id": "11785",
          "scheme": "GMDN"
        },
        {
          "description": "Анатомічні пінцети для розтину",
          "id": "33912100-7",
          "scheme": "ДК021"
        }
      ],
      "status": "active",
      "author": "admin",
      "title": "Test name",
      "description": "Test description"
    }
  ]
}