PATCH /api/0/profiles/8be61f37570947ea860b1c7736a941b7/ HTTP/1.0
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 107
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "access": {
    "token": "9cef3577b1d74e55b8806ea9d0272ede",
    "owner": "admin"
  },
  "data": {
    "title": "New title"
  }
}


200 OK
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 107
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "id": "8be61f37570947ea860b1c7736a941b7",
  "unit": {
    "name": "accounting unit",
    "code": "E50"
  },
  "value": {
    "valueAddedTaxIncluded": true,
    "amount": 50.0,
    "currency": "UAH"
  },
  "criteria": [
    {
      "id": "c718ff18bd694ecbb279c390db0c40d8",
      "requirementGroups": [
        {
          "id": "cbe92155ace044e291cbb97b37a50e4c",
          "requirements": [
            {
              "relatedCriteria_id": "1448221cf4594e69a911b9daa496dde9",
              "expectedValue": "5",
              "title": "Test requirement",
              "description": "Test requirement description"
            }
          ],
          "description": "Test requirement group"
        }
      ],
      "description": "Test description",
      "title": "Test criteria"
    }
  ],
  "images": [
    {
      "sizes": "228",
      "url": "https://test.url"
    }
  ],
  "dateModified": "2020-02-14T13:19:19.738325Z",
  "classification": {
    "description": "Послуги гральних закладів і тоталізаторів",
    "scheme": "ДК021",
    "id": "92350000-9"
  },
  "additionalClassification": [
    {
      "description": "Кишкові щипці",
      "id": "11785",
      "scheme": "GMDN"
    },
    {
      "description": "Анатомічні пінцети для розтину",
      "id": "33912100-7",
      "scheme": "ДК021"
    }
  ],
  "author": "admin",
  "status": "active",
  "title": "New title",
  "description": "Test description"
}