PATCH /api/0/profiles/8be61f37570947ea860b1c7736a941b7/ HTTP/1.0
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 376
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "access": {
    "token": "9cef3577b1d74e55b8806ea9d0272ede",
    "owner": "admin"
  },
  "data": {
    "criteria": [
      {
        "id": "da89935fe34d4580b2bf1974bb39d5cf",
        "requirementGroups": [
          {
            "description": "Requirement group 1",
            "requirements": [
              {
                "title": "Requirement 1",
                "description": "Requirement description 1",
                "relatedCriteria_id": "d0f05bb77cab426b8828a952d27894d9",
                "expectedValue": "5"
              }
            ]
          }
        ]
      }
    ]
  }
}


200 OK
Authorization Basic YWRtaW46YWRtaW5wYXNzd29yZA==
Content-Length 376
Content-Type application/json
Host 127.0.0.1:8000
X-Forwarded-Scheme http
X-Forwarded-Server localhost:80
{
  "id": "8be61f37570947ea860b1c7736a941b7",
  "unit": {
    "name": "accounting unit",
    "code": "E50"
  },
  "value": {
    "valueAddedTaxIncluded": true,
    "amount": 50.0,
    "currency": "UAH"
  },
  "criteria": [
    {
      "id": "da89935fe34d4580b2bf1974bb39d5cf",
      "requirementGroups": [
        {
          "id": "0f296fe0eedf4b01a6839ea7831b6235",
          "requirements": [
            {
              "relatedCriteria_id": "d0f05bb77cab426b8828a952d27894d9",
              "expectedValue": "5",
              "title": "Requirement 1",
              "description": "Requirement description 1"
            }
          ],
          "description": "Requirement group 1"
        }
      ],
      "description": "New description",
      "title": "Completely new title"
    }
  ],
  "images": [
    {
      "sizes": "228",
      "url": "https://test.url"
    }
  ],
  "dateModified": "2020-02-14T13:19:20.111163Z",
  "classification": {
    "description": "Послуги гральних закладів і тоталізаторів",
    "scheme": "ДК021",
    "id": "92350000-9"
  },
  "additionalClassification": [
    {
      "description": "Кишкові щипці",
      "id": "11785",
      "scheme": "GMDN"
    },
    {
      "description": "Анатомічні пінцети для розтину",
      "id": "33912100-7",
      "scheme": "ДК021"
    }
  ],
  "author": "admin",
  "status": "active",
  "title": "New title",
  "description": "Test description"
}